// @ts-check

/**
 * Report generator — creates comparison HTML report
 */

/**
 * Generate an HTML comparison report from quotes
 * @param {Array<import('./caller.js').Quote>} quotes
 * @param {object} jobSpec
 * @param {object} analysis - Result from negotiate.analyzeQuotes
 * @returns {string} HTML string
 */
export function generateReport(quotes, jobSpec, analysis) {
  const sorted = [...quotes].sort((a, b) => a.totalPrice - b.totalPrice);
  const best = sorted[0];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Moving Quote Comparison — ${jobSpec.fromLocation} → ${jobSpec.toLocation}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; background: #f8fafc; color: #1e293b; }
  h1 { font-size: 1.8rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
  h2 { font-size: 1.3rem; margin-top: 2rem; }
  .summary { background: #dbeafe; border: 1px solid #93c5fd; border-radius: 12px; padding: 1.5rem; margin: 1.5rem 0; }
  .summary .price { font-size: 2rem; font-weight: 700; color: #1d4ed8; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { text-align: left; padding: 0.75rem 1rem; border-bottom: 1px solid #e2e8f0; }
  th { background: #f1f5f9; font-weight: 600; }
  tr:hover { background: #f8fafc; }
  .best { background: #dbeafe !important; }
  .best td { font-weight: 600; }
  .red-flag { background: #fee2e2 !important; }
  .red-flag td { color: #b91c1c; }
  .badge { display: inline-block; background: #1d4ed8; color: #fff; font-size: 0.75rem; padding: 2px 8px; border-radius: 999px; margin-left: 0.5rem; }
  .footer { margin-top: 3rem; font-size: 0.85rem; color: #64748b; }
</style>
</head>
<body>
<h1>🚚 Moving Quote Comparison</h1>
<p><strong>Route:</strong> ${jobSpec.fromLocation} → ${jobSpec.toLocation}</p>
<p><strong>Home:</strong> ${jobSpec.bedrooms}-bedroom | <strong>Move date:</strong> ${jobSpec.moveDate || 'Flexible'}</p>
<p><strong>Large items:</strong> ${jobSpec.largeItems.length ? jobSpec.largeItems.join(', ') : 'Standard furniture'}</p>
<p><strong>Stairs:</strong> ${jobSpec.stairsOrigin ? 'Origin ✓' : ''} ${jobSpec.stairsDest ? 'Dest ✓' : ''} ${jobSpec.elevator ? '(elevator available)' : ''}</p>

<div class="summary">
  <h2>🏆 Best Deal</h2>
  <div class="price">$${best.totalPrice.toLocaleString()}</div>
  <p><strong>${best.company}</strong> — ${best.notes?.substring(0, 100) || 'Recommended'}</p>
  <p>${analysis.redFlags.length ? '⚠️ Red flags detected — see notes below' : '✅ All quotes within normal range'}</p>
</div>

<h2>All Quotes (${quotes.length})</h2>
<table>
<thead>
<tr><th>#</th><th>Company</th><th>Base</th><th>Packing</th><th>Stairs</th><th>Fuel</th><th>Insurance</th><th>Total</th><th>Notes</th></tr>
</thead>
<tbody>
${sorted.map((q, i) => {
  const isBest = i === 0;
  const isRedFlag = analysis.redFlags?.some(r => r.includes(q.company));
  return `<tr class="${isBest ? 'best' : ''}${isRedFlag ? ' red-flag' : ''}">
    <td>${i + 1}</td>
    <td>${q.company}${isBest ? ' 🏆' : ''}</td>
    <td>$${q.basePrice}</td>
    <td>$${q.packingFee}</td>
    <td>$${q.stairsFee}</td>
    <td>$${q.fuelFee}</td>
    <td>$${q.insuranceFee}</td>
    <td><strong>$${q.totalPrice.toLocaleString()}</strong></td>
    <td><small>${q.priceChanged ? '💰 Negotiated' : ''} ${isRedFlag ? '⚠️' : ''}</small></td>
  </tr>`;
}).join('\n')}
</tbody>
</table>

${analysis.strategy ? `
<h2>📋 Negotiation Insight</h2>
<div style="background: #f1f5f9; border-radius: 8px; padding: 1rem;">
  <pre style="white-space: pre-wrap; font-family: inherit; margin: 0;">${analysis.strategy}</pre>
</div>` : ''}

${analysis.redFlags.length ? `
<h2>⚠️ Red Flags</h2>
<ul>${analysis.redFlags.map(r => `<li>${r}</li>`).join('\n')}</ul>` : ''}

<h2>💰 Savings Summary</h2>
<p>Price range: <strong>$${sorted[0].totalPrice.toLocaleString()}</strong> – <strong>$${sorted[sorted.length-1].totalPrice.toLocaleString()}</strong></p>
<p>Potential savings vs. highest quote: <strong>$${(sorted[sorted.length-1].totalPrice - sorted[0].totalPrice).toLocaleString()}</strong></p>

<div class="footer">
<p>Generated by <strong>The Negotiator</strong> — Hack-Nation 5th Global AI Hackathon</p>
<p style="font-size: 0.75rem; color: #94a3b8;">Quotes were collected via AI-assisted calling. Verify with companies before booking.</p>
</div>
</body>
</html>`;
}
